/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.IOError;
import java.math.MathContext;
import model.MySQL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manula
 */
public class Address extends javax.swing.JDialog {

    HashMap<String, String> cityMap = new HashMap<>();

    /**
     * Creates new form Address
     */
    private String name;
    private String email;
//    private String id;

    public Address(java.awt.Frame parent, boolean modal, String name, String email) {
        super(parent, modal);
        initComponents();
        empNameLable.setText(name);
        empEmailLable.setText(email);
        this.email = email;
        loadAddress();
        loadCities();
    }

    public void loadAddress() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee_address` "
                    + "INNER JOIN `city` ON `employee_address`.`city_id` = `city`.`id` "
                    + "INNER JOIN `employee` ON `employee_address`.`employee_email` = `employee`.`email` "
                    + "WHERE `email`='" + this.email + "'");

            DefaultTableModel model = (DefaultTableModel) addressTable.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("line1"));
                vector.add(resultSet.getString("line2"));
                vector.add(resultSet.getString("city.name"));
                vector.add(resultSet.getString("employee.first_name"));

                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCities() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `city`");

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                cityMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            cityCombo.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empNameLable = new javax.swing.JLabel();
        empEmailLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aLine1 = new javax.swing.JTextField();
        aLine2 = new javax.swing.JTextField();
        cityCombo = new javax.swing.JComboBox<>();
        addressAddBtn = new javax.swing.JButton();
        AddresssUpBtn = new javax.swing.JButton();
        addressReBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Parchment", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Camera Mart");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camera.png"))); // NOI18N
        jLabel2.setText("Camera Mart");

        jLabel3.setFont(new java.awt.Font("Stencil", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Address");

        empNameLable.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        empNameLable.setText("Employee Name");

        empEmailLable.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        empEmailLable.setText("Employee Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNameLable)
                    .addComponent(empEmailLable))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNameLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empEmailLable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Address Line 1");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Address Line 2");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("City");

        aLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLine1ActionPerformed(evt);
            }
        });

        cityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addressAddBtn.setBackground(new java.awt.Color(0, 102, 204));
        addressAddBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addressAddBtn.setText("Add");
        addressAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressAddBtnActionPerformed(evt);
            }
        });

        AddresssUpBtn.setBackground(new java.awt.Color(204, 204, 0));
        AddresssUpBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        AddresssUpBtn.setForeground(new java.awt.Color(0, 0, 0));
        AddresssUpBtn.setText("Update");
        AddresssUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddresssUpBtnActionPerformed(evt);
            }
        });

        addressReBtn.setBackground(new java.awt.Color(255, 0, 0));
        addressReBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addressReBtn.setText("Remove");
        addressReBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressReBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityCombo, 0, 329, Short.MAX_VALUE)
                    .addComponent(aLine2)
                    .addComponent(aLine1)))
            .addComponent(addressAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddresssUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addressReBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(aLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addressAddBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddresssUpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressReBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Address Line1", "Address Line2", "City", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        addressTable.getTableHeader().setReorderingAllowed(false);
        addressTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(addressTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aLine1ActionPerformed

    private void AddresssUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddresssUpBtnActionPerformed
        String line1 = aLine1.getText();
        String line2 = aLine2.getText();
        String city = String.valueOf(cityCombo.getSelectedItem());

        if (line1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address line1", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address line2", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select a city", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            for (int i = 0; i < addressTable.getRowCount(); i++) {
                String getLine1 = String.valueOf(addressTable.getValueAt(i, 1));
                String getLine2 = String.valueOf(addressTable.getValueAt(i, 2));
                String getCity = String.valueOf(addressTable.getValueAt(i, 3));

                if (getLine1.equals(line1) && getLine2.equals(line2) && getCity.equals(city)) {

                    JOptionPane.showMessageDialog(this, "Updated Succesfully!", "Warning", JOptionPane.WARNING_MESSAGE);

                    loadAddress();
                    reset();
                } else {

                    try {

                        MySQL.executeIUD("UPDATE `employee_address` SET "
                                + "`line1`='" + line1 + "',`line2`='" + line2 + "',`city_id`='" + cityMap.get(city) + "' "
                                + "WHERE `employee_email`='" + this.email + "'");

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    loadAddress();
                    reset();
                }
            }

        }
    }//GEN-LAST:event_AddresssUpBtnActionPerformed

    private void addressAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressAddBtnActionPerformed
        String line1 = aLine1.getText();
        String line2 = aLine2.getText();
        String city = String.valueOf(cityCombo.getSelectedItem());
        long id = System.currentTimeMillis();
        String cm = "CM_EA_";

        if (line1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address line1", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address line2", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select a city", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

//                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee` WHERE `email`='" + this.email + "'");
                boolean isFound = false;

                for (int i = 0; i < addressTable.getRowCount(); i++) {

                    String getLine1 = String.valueOf(addressTable.getValueAt(i, 1));
                    String getLine2 = String.valueOf(addressTable.getValueAt(i, 2));
                    String getCity = String.valueOf(addressTable.getValueAt(i, 3));

                    if (getLine1.equals(line1) && getLine2.equals(line2) && getCity.equals(city)) {
                        JOptionPane.showMessageDialog(this, "Address already added", "Warning", JOptionPane.WARNING_MESSAGE);
                        isFound = true;
                        break;
                    }
                }

                if (!isFound) {

                    MySQL.executeIUD("INSERT INTO `employee_address` (`id`,`line1`,`line2`,`city_id`,`employee_email`) "
                            + "VALUE ('" + cm + "" + id + "','" + line1 + "','" + line2 + "','" + cityMap.get(city) + "','" + this.email + "')");

                    loadAddress();
                    reset();

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_addressAddBtnActionPerformed

    private void addressTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTableMouseClicked
        int row = addressTable.getSelectedRow();

        aLine1.setText(String.valueOf(addressTable.getValueAt(row, 1)));
        aLine2.setText(String.valueOf(addressTable.getValueAt(row, 2)));
        cityCombo.setSelectedItem(String.valueOf(addressTable.getValueAt(row, 3)));

        addressAddBtn.setEnabled(false);

    }//GEN-LAST:event_addressTableMouseClicked

    private void addressReBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressReBtnActionPerformed

        int row = addressTable.getSelectedRow();

        try {

            if (row == -1) {

                JOptionPane.showMessageDialog(this, "Please select a address to delete", "Warning", JOptionPane.WARNING_MESSAGE);

            } else {

                String id = String.valueOf(addressTable.getValueAt(row, 0));

                int deleteConfirm = JOptionPane.showConfirmDialog(this, "Are Your Sure, Do You want to Delete this Address?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (deleteConfirm == JOptionPane.YES_OPTION) {
                    MySQL.executeIUD("DELETE FROM `employee_address` WHERE "
                            + "`id`='" + id + "'");
                    
                    JOptionPane.showMessageDialog(this, "Address Deleted!","Success",JOptionPane.INFORMATION_MESSAGE);
                    
                }

                loadAddress();
                reset();
            }

//            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee_address`"
//                    + " WHERE `employee_email`='" + this.email + "'");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addressReBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddresssUpBtn;
    private javax.swing.JTextField aLine1;
    private javax.swing.JTextField aLine2;
    private javax.swing.JButton addressAddBtn;
    private javax.swing.JButton addressReBtn;
    private javax.swing.JTable addressTable;
    private javax.swing.JComboBox<String> cityCombo;
    private javax.swing.JLabel empEmailLable;
    private javax.swing.JLabel empNameLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        aLine1.setText("");
        aLine2.setText("");
        cityCombo.setSelectedIndex(0);
        aLine1.grabFocus();
        addressAddBtn.setEnabled(true);
    }

}
