/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Manula
 */
public class AddStocks extends javax.swing.JFrame {

    HashMap<String, String> brandMap = new HashMap<>();

    HashMap<String, String> catMap = new HashMap<>();

    public void setBrand(String brand) {
        brandComb.setSelectedItem(brand);
    }

    public void setEmail(String email) {
        empEmail.setText(email);
    }

    /**
     * Creates new form AddProducts
     */
    public AddStocks() {
        initComponents();
        LogIn logIn = new LogIn();
        empEmail.setText(logIn.employeeEmail);
        empName.setText(logIn.employeeName);
        job.setText(logIn.employeeJob);

        reset();
        loadBrand();
        loadcCategories();
        loadStock();
        upStkBtn.setEnabled(false);
    }

    public JButton getSelectDeBtn() {
        return selectDeBtn;
    }

    public JLabel getJLable3() {
        return jLabel3;
    }

    private void loadStock() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `stock` INNER JOIN "
                    + "`product` ON `stock`.`product_id`=`product`.`id`"
                    + "INNER JOIN `brand` ON `brand`.`id`=`product`.`brand_id`"
                    + "INNER JOIN `category` ON `category`.`id`=`product`.`category_id`");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("stock.id"));
                vector.add(resultSet.getString("product.id"));
                vector.add(resultSet.getString("product.name"));
                vector.add(resultSet.getString("brand.name"));
                vector.add(resultSet.getString("category.category"));
                vector.add(resultSet.getString("stock.price"));
                vector.add(resultSet.getString("stock.qty"));

                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadBrand() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `brand`");

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                brandMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            brandComb.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadcCategories() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `category`");

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("category"));
                catMap.put(resultSet.getString("category"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            catComb.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        brandComb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        catComb = new javax.swing.JComboBox<>();
        addBrBtn = new javax.swing.JButton();
        addCtBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addStock = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        priceField = new javax.swing.JFormattedTextField();
        qtyField = new javax.swing.JFormattedTextField();
        clrBtn = new javax.swing.JButton();
        upStkBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        selectDeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();
        empEmail = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        job = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Stocks");

        jLabel11.setFont(new java.awt.Font("Parchment", 1, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camera.png"))); // NOI18N
        jLabel11.setText("Camera Mart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jLabel4.setText("Brand");

        brandComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Category");

        catComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addBrBtn.setBackground(new java.awt.Color(0, 102, 204));
        addBrBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addBrBtn.setText("Add Brand");
        addBrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBrBtnActionPerformed(evt);
            }
        });

        addCtBtn.setBackground(new java.awt.Color(0, 102, 204));
        addCtBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addCtBtn.setText("Add Category");
        addCtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCtBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Product Name");

        jLabel7.setText("Quantity");

        addStock.setBackground(new java.awt.Color(51, 204, 0));
        addStock.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addStock.setForeground(new java.awt.Color(0, 0, 0));
        addStock.setText("Add Stock");
        addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockActionPerformed(evt);
            }
        });

        jLabel8.setText("Unit Price");

        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        priceField.setText("0.00");

        qtyField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        qtyField.setText("0");

        clrBtn.setBackground(new java.awt.Color(255, 255, 0));
        clrBtn.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        clrBtn.setForeground(new java.awt.Color(0, 0, 0));
        clrBtn.setText("Clear All");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        upStkBtn.setBackground(new java.awt.Color(0, 153, 153));
        upStkBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        upStkBtn.setForeground(new java.awt.Color(0, 0, 0));
        upStkBtn.setText("Update Stock");
        upStkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upStkBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jButton1.setText("GRN");

        selectDeBtn.setBackground(new java.awt.Color(0, 153, 153));
        selectDeBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectDeBtn.setForeground(new java.awt.Color(51, 51, 51));
        selectDeBtn.setText("Select a Dealer");
        selectDeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectDeBtnMouseClicked(evt);
            }
        });
        selectDeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDeBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEALER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectDeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(brandComb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(catComb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCtBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upStkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(addStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(catComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBrBtn)
                    .addComponent(addCtBtn)
                    .addComponent(addStock)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upStkBtn)
                    .addComponent(clrBtn)
                    .addComponent(selectDeBtn))
                .addGap(262, 262, 262))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Product ID", "Product Name", "Brand", "Category", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        printBtn.setBackground(new java.awt.Color(204, 0, 0));
        printBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        printBtn.setText("Print Stock Report");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        empEmail.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        empEmail.setText("EMP Email");

        empName.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        empName.setText("EMP Name");

        job.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        job.setText("Job Role");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empEmail)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(empName)
                        .addGap(18, 18, 18)
                        .addComponent(job))
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empName)
                    .addComponent(job))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Suppliers", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBrBtnActionPerformed
        AddBrand ab = new AddBrand(this, true);
        ab.setVisible(true);
        loadBrand();
//        this.setVisible(false);
    }//GEN-LAST:event_addBrBtnActionPerformed

    private void addCtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCtBtnActionPerformed
        AddCat ac = new AddCat(this, true);
        ac.setVisible(true);
        loadcCategories();
//        this.setVisible(false);
    }//GEN-LAST:event_addCtBtnActionPerformed

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed

        String sId = String.valueOf(System.currentTimeMillis());
        String sI = "CM_ST_";

        String stockId = sI + sId;
        String pName = pNameField.getText();
        String brand = String.valueOf(brandComb.getSelectedItem());
        String category = String.valueOf(catComb.getSelectedItem());
        String qty = String.valueOf(qtyField.getText());
        String price = String.valueOf(priceField.getText());

        String pId = String.valueOf(System.currentTimeMillis());
        String pi = "CM_P_ID_";

        if (stockId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stock Id is Empty Please Contact It Consultant", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (pName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Product Name(Model)", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (brand.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Brand", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (category.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select a Category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Available Quantities", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Product Unit Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                MySQL.executeIUD("INSERT INTO `product` (`id`,`name`,`brand_id`,`category_id`) VALUES "
                        + "('" + pi + "" + pId + "','" + pName + "','" + brandMap.get(brand) + "','" + catMap.get(category) + "')");

                MySQL.executeIUD("INSERT INTO `stock` (`id`,`price`,`qty`,`product_id`) "
                        + "VALUES ('" + stockId + "','" + price + "','" + qty + "','" + pi + "" + pId + "')");

                JOptionPane.showMessageDialog(this, "Stock Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);

                this.setVisible(false);
                this.setVisible(true);

                loadStock();
                reset();

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_addStockActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        pNameField.setText(String.valueOf(jTable1.getValueAt(row, 2)));
        brandComb.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 3)));
        catComb.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 4)));
        priceField.setText(String.valueOf(jTable1.getValueAt(row, 5)));
        qtyField.setText(String.valueOf(jTable1.getValueAt(row, 6)));

        addStock.setEnabled(false);
        upStkBtn.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        reset();
    }//GEN-LAST:event_clrBtnActionPerformed

    private void upStkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upStkBtnActionPerformed
        int row = jTable1.getSelectedRow();

        String pId = String.valueOf(jTable1.getValueAt(row, 1));
        String sId = String.valueOf(jTable1.getValueAt(row, 0));
        String proName = pNameField.getText();
        String brand = String.valueOf(brandComb.getSelectedItem());
        String category = String.valueOf(catComb.getSelectedItem());
        Double qty = Double.valueOf(qtyField.getText());
        Double uPrice = Double.valueOf(priceField.getText());

        if (proName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Product Name(Model)", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (brand.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Brand", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (category.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select a Category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Available Quantities", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (uPrice == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Product Unit Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                MySQL.executeIUD("UPDATE `product` SET `name`='" + proName + "',`brand_id`='" + brandMap.get(brand) + "',"
                        + "`category_id`='" + catMap.get(category) + "' WHERE `id`='" + pId + "'");

                MySQL.executeIUD("UPDATE `stock` SET `price`='" + uPrice + "',`qty`='" + qty + "' WHERE `id`='" + sId + "' ");

                JOptionPane.showMessageDialog(this, "Stock Updated", "Success", JOptionPane.INFORMATION_MESSAGE);

                loadStock();
                reset();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_upStkBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `stock` "
                    + "INNER JOIN `product` ON `stock`.`product_id`=`product`.`id` "
                    + "INNER JOIN `brand` ON `product`.`brand_id`=`brand`.`id` "
                    + "INNER JOIN `category` ON `product`.`category_id`=`category`.`id`");

            String path = "src/reports/StockReportCameraMart.jasper";
            HashMap<String, Object> para = new HashMap<>();
            while (resultSet.next()) {

                para.put("Parameter1", empName.getText());
                para.put("COLUMN_0", resultSet.getString("stock.id"));
                para.put("COLUMN_1", resultSet.getString("product.id"));
                para.put("COLUMN_2", resultSet.getString("product.name"));
                para.put("COLUMN_3", resultSet.getString("brand.name"));
                para.put("COLUMN_4", resultSet.getString("category.category"));
                para.put("COLUMN_5", resultSet.getString("stock.price"));
                para.put("COLUMN_6", resultSet.getString("stock.qty"));
            }

            JRTableModelDataSource dataSource = new JRTableModelDataSource(jTable1.getModel());

            JasperPrint jasperPrint = JasperFillManager.fillReport(path, para, dataSource);

            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void selectDeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectDeBtnMouseClicked

    }//GEN-LAST:event_selectDeBtnMouseClicked

    private void selectDeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDeBtnActionPerformed
        Dealers dealers = new Dealers();
        dealers.setVisible(true);
        dealers.setAddstocks(this);
    }//GEN-LAST:event_selectDeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBrBtn;
    private javax.swing.JButton addCtBtn;
    private javax.swing.JButton addStock;
    private javax.swing.JComboBox<String> brandComb;
    private javax.swing.JComboBox<String> catComb;
    private javax.swing.JButton clrBtn;
    private javax.swing.JLabel empEmail;
    private javax.swing.JLabel empName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel job;
    private javax.swing.JTextField pNameField;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JButton printBtn;
    private javax.swing.JFormattedTextField qtyField;
    private javax.swing.JButton selectDeBtn;
    private javax.swing.JButton upStkBtn;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        pNameField.setText("");
        pNameField.grabFocus();
        brandComb.setSelectedIndex(0);
        catComb.setSelectedIndex(0);
        qtyField.setText("0");
        priceField.setText("0.00");
        addStock.setEnabled(true);
        jTable1.clearSelection();
        upStkBtn.setEnabled(false);
    }

}
