/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.StockItem;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Manula
 */
public class AddStocks extends javax.swing.JFrame {

    HashMap<String, String> brandMap = new HashMap<>();
    HashMap<String, StockItem> stockItemMap = new HashMap<>();
    HashMap<String, String> catMap = new HashMap<>();

    public void setBrand(String brand) {
        brandComb.setSelectedItem(brand);
    }

    public void setEmail(String email) {
        empEmail.setText(email);
    }

    /**
     * Creates new form AddProducts
     */
    public AddStocks() {
        initComponents();
        LogIn logIn = new LogIn();
        empEmail.setText(logIn.employeeEmail);
        empName.setText(logIn.employeeName);
        job.setText(logIn.employeeJob);

        reset();
        loadBrand();
        loadCategories();
        loadStock();
        upStkBtn.setEnabled(false);

        this.setExtendedState(MAXIMIZED_BOTH);
    }

    String sId = String.valueOf(System.currentTimeMillis());
    String sI = "CM_ST_";

    String stockId = sI + sId;

    public JTextField getPId() {
        return pIdField;
    }

    public JTextField getProductN() {
        return pNameField;
    }

    public JComboBox getBrCombo() {
        return brandComb;
    }

    public JComboBox getCatCombo() {
        return catComb;
    }

    public JButton getSelectDeBtn() {
        return selectDeBtn;
    }

    public JLabel getMobile() {
        return mobile;
    }

    public JLabel getEmpName() {
        return name;
    }

    private void loadStock() {

        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        modal.setRowCount(0);

        double amount = 0;

        for (StockItem stockItem : stockItemMap.values()) {
            Vector<String> vector = new Vector<>();
            vector.add(stockId);
//            vector.add(product_id);
            vector.add(stockItem.getProName());
            vector.add(stockItem.getBrand());
            vector.add(stockItem.getCategory());
            vector.add(String.valueOf(stockItem.getPrice()));
            vector.add(String.valueOf(stockItem.getQty()));
            vector.add(String.valueOf(stockItem.getTotal()));

            amount += stockItem.getTotal();

            modal.addRow(vector);

        }

        payAmo.setText(String.valueOf(amount));
    }

    public void loadBrand() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `brand`");

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                brandMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            brandComb.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadCategories() {
        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `category`");

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("category"));
                catMap.put(resultSet.getString("category"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            catComb.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        brandComb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        catComb = new javax.swing.JComboBox<>();
        addBrBtn = new javax.swing.JButton();
        addCtBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pIdField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addStock = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        priceField = new javax.swing.JFormattedTextField();
        qtyField = new javax.swing.JFormattedTextField();
        clrBtn = new javax.swing.JButton();
        upStkBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        selectDeBtn = new javax.swing.JButton();
        mobile = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pNameField = new javax.swing.JTextField();
        selectProdBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        roundedPanel1 = new lk.CM.cameraMart.component.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        payAmo = new javax.swing.JFormattedTextField();
        empName = new javax.swing.JLabel();
        job = new javax.swing.JLabel();
        empEmail = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Stocks");

        jLabel11.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camera.png"))); // NOI18N
        jLabel11.setText("Camera Mart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jLabel4.setText("Brand");

        brandComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Category");

        catComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addBrBtn.setBackground(new java.awt.Color(0, 102, 204));
        addBrBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addBrBtn.setText("Add Brand");
        addBrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBrBtnActionPerformed(evt);
            }
        });

        addCtBtn.setBackground(new java.awt.Color(0, 102, 204));
        addCtBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addCtBtn.setText("Add Category");
        addCtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCtBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Product ID");

        pIdField.setEditable(false);
        pIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIdFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity");

        addStock.setBackground(new java.awt.Color(51, 204, 0));
        addStock.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        addStock.setForeground(new java.awt.Color(0, 0, 0));
        addStock.setText("Add Stock");
        addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockActionPerformed(evt);
            }
        });

        jLabel8.setText("Unit Price");

        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        priceField.setText("0.00");

        qtyField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        qtyField.setText("0");

        clrBtn.setBackground(new java.awt.Color(255, 255, 0));
        clrBtn.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        clrBtn.setForeground(new java.awt.Color(0, 0, 0));
        clrBtn.setText("Clear All");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        upStkBtn.setBackground(new java.awt.Color(0, 153, 153));
        upStkBtn.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        upStkBtn.setForeground(new java.awt.Color(0, 0, 0));
        upStkBtn.setText("Update Stock");
        upStkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upStkBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jButton1.setText("GRN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selectDeBtn.setBackground(new java.awt.Color(0, 153, 153));
        selectDeBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectDeBtn.setForeground(new java.awt.Color(51, 51, 51));
        selectDeBtn.setText("Select a Dealer");
        selectDeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectDeBtnMouseClicked(evt);
            }
        });
        selectDeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDeBtnActionPerformed(evt);
            }
        });

        mobile.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        mobile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobile.setText("Mobile");

        name.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name");

        jLabel9.setText("Product Name");

        selectProdBtn.setBackground(new java.awt.Color(0, 153, 153));
        selectProdBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectProdBtn.setForeground(new java.awt.Color(51, 51, 51));
        selectProdBtn.setText("Select a Product");
        selectProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectProdBtnMouseClicked(evt);
            }
        });
        selectProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(pIdField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectDeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(pNameField))
                    .addComponent(selectProdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(catComb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(brandComb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addBrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upStkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile)
                            .addComponent(name))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectDeBtn)
                            .addComponent(selectProdBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStock)
                            .addComponent(jButton1))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upStkBtn)
                            .addComponent(clrBtn))))
                .addGap(187, 187, 187))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(catComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addCtBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBrBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Product Name", "Brand", "Category", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setText("Payable Amount");

        payAmo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        payAmo.setText("0.00");

        empName.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        empName.setText("EMP Name");

        job.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        job.setText("Job Role");

        empEmail.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        empEmail.setText("EMP Email");

        printBtn.setBackground(new java.awt.Color(204, 0, 0));
        printBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        printBtn.setText("Save Stock");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empEmail)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(empName)
                                .addGap(18, 18, 18)
                                .addComponent(job))
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payAmo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(payAmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empName)
                    .addComponent(job))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(printBtn))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Stock", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Suppliers", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBrBtnActionPerformed
        AddBrand ab = new AddBrand(this, true);
        ab.setVisible(true);
        loadBrand();
//        this.setVisible(false);
    }//GEN-LAST:event_addBrBtnActionPerformed

    private void addCtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCtBtnActionPerformed
        AddCat ac = new AddCat(this, true);
        ac.setVisible(true);
        loadCategories();
//        this.setVisible(false);
    }//GEN-LAST:event_addCtBtnActionPerformed

    public String pId(String product_id) {

        return null;
    }

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed

        String pId = pIdField.getText();
        String pName = pNameField.getText();
        String brand = String.valueOf(brandComb.getSelectedItem());
        String category = String.valueOf(catComb.getSelectedItem());
        String qty = qtyField.getText();
        String price = priceField.getText();
        String amount = payAmo.getText();
//        String pid = product_id;

        Double total = Double.parseDouble(qty) * Double.parseDouble(price);

        StockItem stockItem = new StockItem();
        stockItem.setProName(pName);
        stockItem.setBrand(brand);
        stockItem.setCategory(category);
        stockItem.setQty(Integer.parseInt(qty));
        stockItem.setTotal(total);
        stockItem.setPrice(Double.parseDouble(price));
        stockItem.setpId(pId);
        stockItem.setAmount(Double.parseDouble(amount));

        if (stockId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stock Id is Empty Please Contact It Consultant", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (pName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select a Product", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (brand.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please enter Brand", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (category.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please Select a Category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty.equals(0) || qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Available Quantities", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (price.equals("0.00") || price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Product Unit Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            reset();
            loadStock();
            if (stockItemMap.get(pId) == null) {
                stockItemMap.put(pId, stockItem);

                loadStock();
                reset();

            }

//            StockItem found = stockItemMap.get(product_id);
//
//            if (found.getPrice(Double.parseDouble(price)) == Double.parseDouble(price)) {
//                found.setQty(found.getQty() + Integer.parseInt(qty));
//                loadStock();
//            }
//
//            loadStock();
//            reset();
//        
//            try {
//                MySQL.executeIUD("INSERT INTO `product` (`id`,`name`,`brand_id`,`category_id`) VALUES "
//                        + "('" + pi + "" + pId + "','" + pName + "','" + brandMap.get(brand) + "','" + catMap.get(category) + "')");
//
//                MySQL.executeIUD("INSERT INTO `stock` (`id`,`price`,`qty`,`product_id`) "
//                        + "VALUES ('" + stockId + "','" + price + "','" + qty + "','" + pi + "" + pId + "')");
//
//                JOptionPane.showMessageDialog(this, "Stock Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
//                this.setVisible(false);
//                this.setVisible(true);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
        }

    }//GEN-LAST:event_addStockActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        pIdField.setText(String.valueOf(jTable1.getValueAt(row, 2)));
        pNameField.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        brandComb.setSelectedItem(jTable1.getValueAt(row, 2));
        catComb.setSelectedItem(jTable1.getValueAt(row, 3));
        priceField.setText(String.valueOf(jTable1.getValueAt(row, 5)));
        qtyField.setText(String.valueOf(jTable1.getValueAt(row, 6)));

        addStock.setEnabled(false);
        upStkBtn.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        reset();
    }//GEN-LAST:event_clrBtnActionPerformed

    private void upStkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upStkBtnActionPerformed
        int row = jTable1.getSelectedRow();

        String pId = String.valueOf(jTable1.getValueAt(row, 1));
        String sId = String.valueOf(jTable1.getValueAt(row, 0));
        String proName = pIdField.getText();
        String brand = String.valueOf(brandComb.getSelectedItem());
        String category = String.valueOf(catComb.getSelectedItem());
        Double qty = Double.parseDouble(qtyField.getText());
        Double uPrice = Double.valueOf(priceField.getText());

        if (proName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Product Name(Model)", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (brand.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Brand", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (category.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select a Category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Available Quantities", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (uPrice == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Product Unit Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                MySQL.executeIUD("UPDATE `product` SET `name`='" + proName + "',`brand_id`='" + brandMap.get(brand) + "',"
                        + "`category_id`='" + catMap.get(category) + "' WHERE `id`='" + pId + "'");

                MySQL.executeIUD("UPDATE `stock` SET `price`='" + uPrice + "',`qty`='" + qty + "' WHERE `id`='" + sId + "' ");

                JOptionPane.showMessageDialog(this, "Stock Updated", "Success", JOptionPane.INFORMATION_MESSAGE);

                loadStock();
                reset();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_upStkBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed

        String pName = pIdField.getText();
        String brand = String.valueOf(brandComb.getSelectedItem());
        String category = String.valueOf(catComb.getSelectedItem());
        String qty = qtyField.getText();
        String price = priceField.getText();
        String pid = pIdField.getText();

        Double total = Double.parseDouble(qty) * Double.parseDouble(price);

        StockItem stockItem = new StockItem();
        stockItem.setProName(pName);
        stockItem.setBrand(brand);
        stockItem.setCategory(category);
        stockItem.setQty(Integer.parseInt(qty));
        stockItem.setTotal(total);
        stockItem.setPrice(Double.parseDouble(price));
        stockItem.setpId(pid);

        try {

            String empName = this.empName.getText();
            stockItem.setEmpName(empName);

//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            for (StockItem addStockItem : stockItemMap.values()) {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `stock` "
                        + "WHERE `price`='" + addStockItem.getPrice() + "' AND "
                        + "`qty`='" + addStockItem.getQty() + "' AND "
                        + "`product_id`='" + addStockItem.getpId() + "'");

                String sid = "";

                if (resultSet.next()) {
                    sid = resultSet.getString("id");

                    String currentQty = resultSet.getString("qty");
                    String updatedQuantity = String.valueOf(Double.parseDouble(currentQty) + addStockItem.getQty());
                    MySQL.executeIUD("UPDATE `stock` SET `qty` = '" + updatedQuantity + "' WHERE `st_id` = '" + sid + "'");
                } else {
                    // new stock

                    MySQL.executeIUD("INSERT INTO `stock`(`st_id`,`price`,`qty`,`product_id`) "
                            + "VALUES('" + stockId + "','" + addStockItem.getPrice() + "','" + addStockItem.getQty() + "',"
                            + "'" + addStockItem.getpId() + "')");

                    name.setText("Name");
                    mobile.setText("Mobile");
                    reset();
                    tableReset();

                    JOptionPane.showMessageDialog(this, "Stock Saved", "Success", JOptionPane.INFORMATION_MESSAGE);

                    ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `stock` WHERE "
                            + "`price`= '" + addStockItem.getPrice() + "' AND "
                            + "`qty`='" + addStockItem.getQty() + "' AND "
                            + "`product_id`='" + addStockItem.getpId() + "'");

                    if (resultSet2.next()) {
                        sid = resultSet2.getString("id");
                    }
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void selectDeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectDeBtnMouseClicked

    }//GEN-LAST:event_selectDeBtnMouseClicked

    private void selectDeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDeBtnActionPerformed
        Dealers dealers = new Dealers();
        dealers.setVisible(true);
        dealers.setAddstocks(this);

    }//GEN-LAST:event_selectDeBtnActionPerformed

    private void selectProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectProdBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectProdBtnMouseClicked

    private void selectProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProdBtnActionPerformed
        Products products = new Products();
        products.setVisible(true);
        products.setAddStocks(this);
    }//GEN-LAST:event_selectProdBtnActionPerformed

    private void pIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIdFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

//            String pid = pIdField.getText();
//            String proName = pNameField.getText();
//            String cat = String.valueOf(catComb.getSelectedItem());
//            String brand = String.valueOf(brandComb.getSelectedItem());
//            Integer qty = Integer.parseInt(qtyField.getText());
//            Double price = Double.parseDouble(priceField.getText());
//            if (pid.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Please Select a Product", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else if (proName.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Please Select a Product", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else if (cat.equals("Select")) {
//                JOptionPane.showMessageDialog(this, "Please Select a Category", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else if (brand.equals("Select")) {
//                JOptionPane.showMessageDialog(this, "Please Select a Brand", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else if (qty.equals(0)) {
//                JOptionPane.showMessageDialog(this, "Please Enter Quantity", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else if (price.equals(0.00)) {
//                JOptionPane.showMessageDialog(this, "Please Enter Price", "Warning", JOptionPane.WARNING_MESSAGE);
//            } else {
            DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
            if (modal.getRowCount() >= 1) {
                String grn = String.valueOf(System.currentTimeMillis());
                String id = "GRN_";
                String grn_id = grn + id;

                String payableAmo = payAmo.getText();
                String mobile = this.mobile.getText();

                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                MySQL.executeIUD("INSERT INTO `grn` (`id`,`date_and_time`,`paid_amount`,`dealer_mobile`,`employee_email`) "
                        + "VALUES ('" + grn_id + "','" + sdf.format(date) + "','" + payableAmo + "','" + mobile + "','" + empEmail.getText() + "')");

//                System.out.println(empEmail.getText());
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `stock` "
                        + "INNER JOIN `product` ON `product`.`id` = `stock`.`product_id` "
                        + "INNER JOIN `brand` ON `brand`.`id` = `product`.`brand_id` "
                        + "INNER JOIN `category` ON `category`.`id` = `product`.`category_id`");

                StockItem stockItem = new StockItem();

                String path = "src/reports/StockReportCameraMart.jasper";
                HashMap<String, Object> para = new HashMap<>();
                
                stockItem.setEmpName(empName.getText());
                
                while (resultSet.next()) {

                    String total = resultSet.getString("stock.price");
                    String qty = resultSet.getString("stock.qty");
                    double tot = Double.parseDouble(total) * Double.parseDouble(qty);
                    stockItem.setTotal(tot);

                    para.put("Parameter1", stockItem.getEmpName());
                    para.put("COLUMN_0", resultSet.getString("stock.id"));
                    para.put("COLUMN_1", stockItem.getProName());
                    para.put("COLUMN_2", resultSet.getString("brand.name"));
                    para.put("COLUMN_3", resultSet.getString("category.category"));
                    para.put("COLUMN_4", resultSet.getString("stock.price"));
                    para.put("COLUMN_5", resultSet.getString("stock.qty"));
                    para.put("COLUMN_6", stockItem.getTotal());

                }

                JRTableModelDataSource dataSource = new JRTableModelDataSource(jTable1.getModel());

                JasperPrint jasperPrint = JasperFillManager.fillReport(path, para, dataSource);

                JasperViewer.viewReport(jasperPrint, false);
//                if (resultSet.next()) {
//                    System.out.println("Success!");
//                }

                JOptionPane.showMessageDialog(this, "success", "Success", JOptionPane.INFORMATION_MESSAGE);
                reset();
                tableReset();
            } else {
                JOptionPane.showMessageDialog(this, "Your Stocks are Empty! Please add stocks to generate a GRN Report.", "Warning", JOptionPane.WARNING_MESSAGE);
            }

//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBrBtn;
    private javax.swing.JButton addCtBtn;
    private javax.swing.JButton addStock;
    private javax.swing.JComboBox<String> brandComb;
    private javax.swing.JComboBox<String> catComb;
    private javax.swing.JButton clrBtn;
    private javax.swing.JLabel empEmail;
    private javax.swing.JLabel empName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel job;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JTextField pIdField;
    private javax.swing.JTextField pNameField;
    private javax.swing.JFormattedTextField payAmo;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JButton printBtn;
    private javax.swing.JFormattedTextField qtyField;
    private lk.CM.cameraMart.component.RoundedPanel roundedPanel1;
    private javax.swing.JButton selectDeBtn;
    private javax.swing.JButton selectProdBtn;
    private javax.swing.JButton upStkBtn;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        pIdField.setText("");
        selectDeBtn.grabFocus();
        pNameField.setText("");
        brandComb.setSelectedIndex(0);
        catComb.setSelectedIndex(0);
        qtyField.setText("0");
        priceField.setText("0.00");
        addStock.setEnabled(true);
        jTable1.clearSelection();
        upStkBtn.setEnabled(false);
    }

    private void tableReset() {
        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        if (modal.getRowCount() >= 1) {
            modal.setRowCount(0);
        }
    }

}
